[target.xtensa-esp32-espidf]
runner = "espflash flash --monitor"
linker = "ldproxy"

#runner = "espflash flash --monitor --speed 921600 /dev/ttyUSB1" # Select this runner for espflash v2.x.x
[target.xtensa-esp32-none-elf]
linker = "ldproxy"
[target.riscv32imc-esp-espidf]
linker = "ldproxy"

[env]
ESP_LOGLEVEL="INFO"
ESP_IDF_SYS_ROOT_CRATE="zenoh-pico-rs"
# Use the ESP-IDF installation's own tools, not the Rust esp toolchain
IDF_PATH="/home/lieven/esp/esp-idf"
ESP_IDF_TOOLS_INSTALL_DIR="fromenv"

[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]
