[package]
name = "akka"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", default-features = false, features = [ "macros", "rt-multi-thread"] }
async-trait="0.1.88"
thiserror="*"
env_logger="*"
log="*"
chrono="*"
base64="*"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
serde_cbor ="*"
anyhow="1.0.98"
clap = { version = "4.5.26", features = ["derive"] }
basu="*"
