[package]
name = "zenoh-linux-eventbus-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", default-features = false, features = [ "macros", "rt-multi-thread"] }
async-trait="0.1.88"
thiserror="*"
env_logger="*"
log="*"
chrono="*"
base64="*"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
serde_cbor ="*"
anyhow="1.0.98"
clap = { version = "4.5.26", features = ["derive"] }
basu="*"
zenoh = {version = "1.3.4"}
hidapi ={ version = "2.6", optional=true,features = ["linux-static-hidraw"] }
bluer ={ version="*",optional=true,features=["bluetoothd"]}
hostname = "*"
statig = "0.4.1"
# fsm = { version = "0.3.0", optional=true }

[features]
default = ["with-fsm"]
with-ps4 = ["dep:bluer", "dep:hidapi"]  # Features to enable PS4 controller support, also controls crate dependencies
with-fsm = []
