[package]
name = "zenoh-ps4-linux"
version = "0.1.0"
edition = "2024"

[dependencies]
gilrs = "0.10.10"
zenoh = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
hidapi ={ version = "2.6", features = ["linux-static-hidraw"] }