[target.xtensa-esp32-none-elf]
runner = "espflash  --monitor --speed 921600 /dev/ttyUSB0" # Select this runner for espflash v2.x.x

[env]
ESP_LOGLEVEL="INFO"
[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",

  "-C", "link-arg=-Trom_functions.x",

  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"
runner = "espflash flash --baud=921600 --monitor /dev/ttyUSB0"
[unstable]
build-std = ["alloc", "core"]
