[package]
name = "zenoh_ws_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-rt = "2.11.0"
actix-web = "4.11.0"
actix-files = "0.6"
actix-web-actors = "4.3.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
base64 = "0.22"
zenoh = "1.5.1"   # âœ… current async crate from Eclipse Zenoh
log = "0.4"
env_logger = "0.11.8"
chrono = { version = "0.4", features = ["serde"] }
